#[cfg(target_os = "macos")]
pub(crate) fn get_ascii_art() -> Box<&'static [&'static str]> {
    const ASCII_ARRAY: &[&str] = &[r#"                 ,MMMM.
               .MMMMMM
               MMMMM,
     .;MMMMM:' MMMMMMMMMM;.
   MMMMMMMMMMMMNWMMMMMMMMMMM:
 .MMMMMMMMMMMMMMMMMMMMMMMMWM.
 MMMMMMMMMMMMMMMMMMMMMMMMM.
;MMMMMMMMMMMMMMMMMMMMMMMM:
:MMMMMMMMMMMMMMMMMMMMMMMM:
.MMMMMMMMMMMMMMMMMMMMMMMMM.
 MMMMMMMMMMMMMMMMMMMMMMMMMMM.
 .MMMMMMMMMMMMMMMMMMMMMMMMMMMM
  .MMMMMMMMMMMMMMMMMMMMMMMMMM.
    MMMMMMMMMMMMMMMMMMMMMMMM
     ;MMMMMMMMMMMMMMMMMMMM.
       .MMMM,.    .MMMM,."#];

    Box::new(ASCII_ARRAY)
}

#[cfg(target_os = "windows")]
pub(crate) fn get_ascii_art() -> Box<&'static [&'static str]> {
    const ASCII_ARRAY: &[&str] = &[r#"WWWWWWWWWWWWWW  WWWWWWWWWWWWWW
WWWWWWWWWWWWWW  WWWWWWWWWWWWWW
WWWWWWWWWWWWWW  WWWWWWWWWWWWWW
WWWWWWWWWWWWWW  WWWWWWWWWWWWWW
WWWWWWWWWWWWWW  WWWWWWWWWWWWWW
WWWWWWWWWWWWWW  WWWWWWWWWWWWWW
WWWWWWWWWWWWWW  WWWWWWWWWWWWWW

WWWWWWWWWWWWWW  WWWWWWWWWWWWWW
WWWWWWWWWWWWWW  WWWWWWWWWWWWWW
WWWWWWWWWWWWWW  WWWWWWWWWWWWWW
WWWWWWWWWWWWWW  WWWWWWWWWWWWWW
WWWWWWWWWWWWWW  WWWWWWWWWWWWWW
WWWWWWWWWWWWWW  WWWWWWWWWWWWWW
WWWWWWWWWWWWWW  WWWWWWWWWWWWWW"#];

    Box::new(ASCII_ARRAY)
}

#[cfg(target_os = "linux")]
pub(crate) fn get_ascii_art() -> Box<&[&'static str]> {
    //todo
}

#[cfg(target_os = "netbsd")]
pub(crate) fn get_ascii_art() -> Box<&[&'static str]> {
    //todo
}
