spacing = 2
padding = 0
hide_ascii = true
prefer_small_ascii = false
separator = ">"
key_color = "Cyan"
separator_color = "White"
palette = "Light"

[bar]
glyph = "ß‹"
symbol_open = '['
symbol_close = ']'
hide_delimiters = true
visible = true

[box]
border = "plain"
visible = true

[box.inner_margin]
x = 1
y = 0

[custom_ascii]
color = "Green"
# path = "~/pro/rust/macchina/ascii/rust.ascii"

[randomize]
key_color = false
separator_color = false

[keys]
host = "Host"
kernel = "Kernel"
battery = "Battery"
os = "OS"
de = "DE"
wm = "WM"
distro = "Distro"
terminal = "Terminal"
shell = "Shell"
packages = "Packages"
uptime = "Uptime"
memory = "Memory"
machine = "Machine"
local_ip = "Local IP"
backlight = "Brightness"
resolution = "Resolution"
cpu_load = "CPU Load"
cpu = "CPU"
